### ISSUE TITLE
Why Rhino?

### ISSUE THREAD

**Issue by Klypse** [nonever99/Rhino-js-SHA-256#1]
Hi, const newbie.
I just can't understand why the fuck you're using `Rhino`
How come you were going on?

**Comment by nonever99** [comment]
> Hi, const newbie.
> I just can't understand why the fuck you're using `Rhino`
> How come you were going on?

`So what`

**Comment by dev-kiri** [comment]
> > Hi, const newbie.
> > I just can't understand why the fuck you're using `Rhino`
> > How come you were going on?
> 
> `So what`

WTF

**Comment by dev-kiri** [comment]
> > Hi, const newbie.
> > I just can't understand why the fuck you're using `Rhino`
> > How come you were going on?
> 
> `So what`

YOU'RE JUST COMPLETE SAVAGE
